#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=$(getApplication)

runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication "$application"
runApplication postProcess -func probes
runApplication postProcess -func vorticity

#------------------------------------------------------------------------------
